[package]
authors = ["Triton Software"]
edition = "2021"
name = "neptune-core"
version = "0.0.0"
default-run = "neptune-core"
publish = false

[dev-dependencies.cargo-husky]
default-features = false                                           # Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-clippy", "run-cargo-fmt"]
version = "1"

[dependencies]
aead = "0"
aes-gcm = "0"
bech32 = "0"
field_count = "0.1.1"
anyhow = "1"
bincode = "1"
bytes = "1"
chrono = "0"
clap = { version = "4", features = ["derive"] }
directories = "4"
futures = "0"
itertools = "0"
memmap2 = "0"
num-bigint = { version = "0", features = ["serde"] }
num-traits = "0"
rand = "0"
rusty-leveldb = { git = "https://github.com/dermesser/leveldb-rs.git", branch = "do-more-compactions" }
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"
tarpc = { version = "0", features = ["tokio1", "serde-transport", "tcp"] }
tokio = { version = "1", features = ["full", "tracing"] }
tokio-serde = { version = "0", features = ["bincode", "json"] }
tokio-util = { version = "0", features = ["codec"] }
tracing = "0"
tracing-subscriber = { version = "0", features = [
    "std",
    "env-filter",
    "time",
    "fmt",
] }
tracing-test = "0"
# triton-vm = "0.31.1"
triton-vm = { git = "https://github.com/TritonVM/triton-vm.git", branch = "thv/do-more-compaction" }
# triton-opcodes = "0.31.0"
twenty-first = { git = "https://github.com/Neptune-Crypto/twenty-first.git", branch = "thv/do-more-compactions" }
# twenty-first = "0.30.0"
# tasm-lib = "0.1.0"
tasm-lib = { git = "https://github.com/TritonVM/tasm-lib.git", branch = "thv/do-more-compactions" }
priority-queue = "1"
get-size = { version = "0", features = ["derive"] }
num-rational = "0"
bytesize = "1"
tui = "0"
crossterm = "0"
unicode-width = "0"
strum = "0"
strum_macros = "0"

[dev-dependencies]
pin-project-lite = "0"
tokio-test = "0"

# needed because it otherwise takes too long to sign transaction with STARK proofs
[profile.dev.package.triton-vm]
opt-level = 3

[profile.release.package.triton-vm]
opt-level = 3

[profile.bench.package.triton-vm]
opt-level = 3

[profile.test.package.triton-vm]
opt-level = 3

# [profile.test]
# opt-level = 0 # change to 3 for shorter test running times but much longer test compilation time
# debug = true
# debug-assertions = true
# overflow-checks = true
# lto = false
# incremental = true
# codegen-units = 256
# rpath = false
